# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               HorseGeneAnnotation
tagline:             'Crowd sourcing the equine genome'
description:         'Crowd sourcing the equine genome'
#baseurl:             'https://umn-eggl.github.io/HorseGeneAnnotation'
url:                 https://umn-eggl.github.io/
baseurl:             HorseGeneAnnotation/
include:             ['_pages']
kramdown:            
  input:             GFM
paginate:            5

# About/contact
author:
  name:              Rob Schaefer
  url:               https://twitter.com/CSciBio
  email:             rob@linkage.io

# Custom vars
version:             1.0.0
